title: Stool Design
description: D&I Industrial Design 2021

theme: minima
# theme: jekyll-theme-cayman

page_gen:
- data: 'ikea'
  template: 'project'
  name: 'name'
  dir: 'projects/2020-ikea-hacker'
